language: objective-c

xcode_workspace: RiotKit.xcworkspace
xcode_scheme: RiotKit
osx_image: xcode8.2
xcode_sdk: iphonesimulator9.1

script:
  - xcodebuild -workspace RiotKit/RiotKit.xcworkspace -scheme RiotKit -destination 'platform=iOS Simulator,OS=10.2, name=iPhone 5s' clean build test

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'RiotKit'
